
name: Build and Release CalendarBot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup Bun
    - name: Install Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 'latest'

    # Install dependencies
    - name: Install dependencies
      run: bun install

    # Build the Bun application targeting Node.js
    - name: Build CalendarBot (Target Node)
      run: bun build index.ts --target=node

    # Setup Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Login to Docker Hub or your container registry (optional if not required)
    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker image for Node.js runtime
    - name: Build Docker Image
      run: |
        docker build -t VicPetrov/calendarbot:latest .
        docker tag VicPetrov/calendarbot:latest VicPetrov/calendarbot:${{ github.sha }}
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Upload Docker image to GitHub releases as an artifact
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.sha }}
        name: Release ${{ github.sha }}
        files: |
          Dockerfile
